version: 2
sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  apt_packages:
    - graphviz

formats:
  - htmlzip

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
